import Link from "next/link";
import { IntentViatorCards } from "@/components/IntentViatorCards";
import type { PortIntentGuide } from "@/lib/port-intent-guides";
import styles from "./OsakaKaiyukanArticle.module.css";

export function OsakaKaiyukanArticle({ guide }: { guide: PortIntentGuide }) {
  return <div className={styles.guide} data-kaiyukan-article="entry-time-decision">
      <p><strong>Yes—if your ship is confirmed at Tempozan and an available timed ticket fits your return deadline.</strong> Kaiyukan is a nearby independent outing; allow about two hours inside, plus your actual terminal exit, walking, admission and return allowances. The Japan Tourism Agency places Tempozan Harbor Village, which contains the aquarium, next to Osaka port. However, proximity alone does not make a ticket usable: you need an admission slot that leaves room for the visit, the walk back and your ship&#x27;s boarding instructions. This advice does not apply automatically to another Osaka berth. <a href="https://www.mlit.go.jp/kankocho/cruise/detail/029/documents/kanko.pdf" target="_blank" rel="noopener noreferrer">Official port-area guide, page 2</a>.</p>
      <p>The key decision is <strong>which entry time fits</strong>, not how many attractions you can add. Osaka&#x27;s tourism bureau suggests 120 minutes for the aquarium visit. Treat that as a reference for time inside, not a ship-to-ship excursion duration. <a href="https://osaka-info.jp/en/spot/osaka-aquarium-kaiyukan/" target="_blank" rel="noopener noreferrer">Osaka Convention &amp; Tourism Bureau</a>.</p>
    <figure className={styles.photo}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src="/media/editorial/kaiyukan-whale-shark.webp" srcSet="/media/editorial/kaiyukan-whale-shark-640.webp 640w, /media/editorial/kaiyukan-whale-shark.webp 1200w" sizes="(max-width: 820px) calc(100vw - 40px), 780px" alt="Whale shark swimming among fish inside Osaka Aquarium Kaiyukan" width={1200} height={904} loading="lazy" decoding="async" />
      <figcaption>An archival view inside Kaiyukan, photographed in 2010. <small>Photo: <a href="https://commons.wikimedia.org/wiki/File:Osaka_Aquarium_Kaiyukan_(5262933558).jpg" target="_blank" rel="noopener noreferrer">Kimon Berlin / Wikimedia Commons</a> · <a href="https://creativecommons.org/licenses/by-sa/2.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 2.0</a>. Color adjustment: Togabi; resized for web.</small></figcaption>
    </figure>
    <section>
      <h2>Check the berth before buying the nearby attraction</h2>
      <p>Read the berth in your cruise documents and ask the ship which passenger exit will be used. Japan&#x27;s official port guide lists both Tempozan and Central Pier North; a booking that says only “Osaka” is not sufficient to assume this walking plan. The aquarium&#x27;s destination address is <strong>1-1-10 Kaigandori, Minato-ku, Osaka City</strong>. Save it with the ship&#x27;s return entrance, not just a generic Osaka port map pin. <a href="https://www.mlit.go.jp/kankocho/cruise/detail/029/index.html" target="_blank" rel="noopener noreferrer">Port information</a>; <a href="https://osaka-info.jp/en/spot/osaka-aquarium-kaiyukan/" target="_blank" rel="noopener noreferrer">aquarium address</a>.</p>
      <p>From a confirmed Tempozan passenger exit, ask terminal staff for the current public walking route to Kaiyukan in Tempozan Harbor Village. You do not need to take a city train just to reach this neighboring attraction. Follow the permitted exit route rather than crossing a working berth to follow the shortest line on a map. This guide does not promise a fixed gangway-to-door walking time: the assigned ship position, clearance and exit arrangements matter.</p>
      <p>If you are approaching from elsewhere in Osaka, the tourism bureau describes a five-minute walk from <strong>Osakako station, Exit 1, on the Chuo Line</strong>. That is a station-to-attraction reference, not a five-minute guarantee from your ship, nor confirmation that Exit 1 is your accessible route. A different berth requires a separately checked journey in both directions. <a href="https://osaka-info.jp/en/spot/osaka-aquarium-kaiyukan/" target="_blank" rel="noopener noreferrer">Official attraction access</a>.</p>
    </section>
    <section>
      <h2>Work backward to find your latest useful entry time</h2>
      <p>Start with the ship&#x27;s required return time, then subtract your return walk, terminal procedures, a contingency allowance and the time you want inside. Choose an admission slot only after that calculation. Do not use the ship&#x27;s later departure time as a return deadline.</p>
      <p>Here is an <strong>illustrative calculation, not a sailing schedule or official minimum</strong>. Suppose your own plan requires you to be back at the terminal at 14:00, after already protecting the ship&#x27;s boarding deadline. If you reserve 30 minutes to leave the attraction and reach that return point, plus 30 minutes of contingency, the aquarium visit must end by 13:00. A two-hour visit then requires entry by 11:00. A remaining 12:30 ticket would not fit that plan, despite the aquarium being nearby.</p>
      <p>Use your group&#x27;s actual walking and assistance needs in place of those example allowances. Separately check whether you can reach the entrance after the ship clears and before the chosen slot. If clearance is delayed, shorten or abandon the outing; do not recover the lost time by removing the return allowance.</p>
      <p>Check the aquarium&#x27;s <a href="https://www.kaiyukan.com/info/hours/" target="_blank" rel="noopener noreferrer">operating calendar</a> for your visit date. An early ship arrival does not imply that the aquarium is open, and general seasonal hours are not a substitute for that day&#x27;s calendar. If the first available entry is too late, keep the day local without buying an aquarium ticket you cannot use comfortably.</p>
    </section>
    <section>
      <h2>Choose the ticket only after the time fits</h2>
      <p>Kaiyukan&#x27;s own ticket page says admission uses variable pricing and recommends advance e-tickets with a specified date and time. It also warns that a same-day ticket may not allow entry at your preferred time. Check the date, slot, age categories and total in <strong>Japanese yen (JPY)</strong> before payment; this guide does not quote a fixed current admission price. <a href="https://www.kaiyukan.com/info/ticket/kaiyukan/" target="_blank" rel="noopener noreferrer">Official tickets and price calendar</a>.</p>
      <p>For a family, total the tickets for each traveler rather than multiplying an adult headline price by everyone. Add any food, transport from a different berth and optional activities separately. A ticket for the aquarium is not evidence of cruise-terminal pickup or an escorted return.</p>
      <p>For official e-tickets, Kaiyukan specifies <strong>15-minute entry slots</strong> and asks you to sign in to Webket before adding tickets. If you are late, first try changing the time in Webket. The aquarium says late visitors can still enter if a change is unavailable, but people booked for that slot have priority, so you may wait. That is not a reason to book a slot your ship is unlikely to meet. <a href="https://www.kaiyukan.com/about/news/20582.html" target="_blank" rel="noopener noreferrer">Official e-ticket instructions</a>.</p>
      <p>The same official instructions say credit-card purchases can be self-cancelled in Webket through the visit day without a cancellation fee, except after a receipt has been issued; refund timing depends on the card company. Recheck the terms attached to your purchase, especially with a different seller. A missed port call does not itself submit a cancellation. Save your confirmation and account access before going ashore.</p>
      <p>Start from the aquarium&#x27;s own ticket page: its <a href="https://www.kaiyukan.com/about/news/20615.html" target="_blank" rel="noopener noreferrer">June 12, 2026 notice</a> warns about impersonating ticket sites and names the official website, Klook, KKday and Trip.com as authorized routes. This guide links the official page rather than an unverified seller.</p>
      <p>For this local outing, start with the official admission option. A private guide or transfer is useful only if it solves a real access or assistance need and explicitly covers your berth, date and return. A broad Osaka sightseeing product is not a substitute for a matching aquarium ticket.</p>
    </section>
    <section>
      <h2>Children and walking needs can change the time budget</h2>
      <p>Kaiyukan recommends leaving strollers at its designated entrance-area storage, although permitted strollers can be brought inside. Its guidance notes that most of the route is sloped, with some stairs and escalators, and asks visitors needing an elevator route to speak to staff. Check the current permitted stroller types before arrival. The entrance building&#x27;s second-floor baby-care room has feeding and changing facilities. Allow time for care stops rather than treating the two-hour visit reference as a family deadline. <a href="https://www.kaiyukan.com/info/area/nursing/" target="_blank" rel="noopener noreferrer">Official family facilities</a>.</p>
      <p>The aquarium lists a limited supply of loan wheelchairs and staff-assisted elevator guidance when needed. Its published accessible toilets include the entrance building&#x27;s second floor before admission and the sixth floor inside. These facilities do <strong>not</strong> establish step-free access from your ship&#x27;s gangway through the terminal to the aquarium. Confirm that separate approach with the cruise line, and discuss equipment or assistance needs directly with the attraction. <a href="https://www.kaiyukan.com/info/area/barrierfree/" target="_blank" rel="noopener noreferrer">Official accessibility information</a>.</p>
      <p><strong>Rolling suitcases cannot go into the aquarium.</strong> Kaiyukan&#x27;s <a href="https://www.kaiyukan.com/about/news/20515.html" target="_blank" rel="noopener noreferrer">luggage rules effective April 24, 2026</a> prohibit carry cases and carts, as well as oversized items. Its <a href="https://www.kaiyukan.com/assets/pdf/rule/list_of_rule_changes.pdf" target="_blank" rel="noopener noreferrer">illustrated rules</a> distinguish permitted strollers and walking aids from luggage carts. On a normal port call, leave cruise luggage aboard. On disembarkation day, arrange storage and its collection time before buying admission; do not assume that a suitably sized locker will be free.</p>
    </section>
    <section>
      <h2>Make the aquarium the outing, then reassess</h2>
      <p><strong>Plan one continuous aquarium visit.</strong> <a href="https://www.kaiyukan.com/about/news/20564.html" target="_blank" rel="noopener noreferrer">Kaiyukan ended re-entry on June 15, 2026</a>, so do not schedule lunch outside halfway through and expect to return on the same admission. If your entry slot, visit and return fit, let Kaiyukan be the main commitment. After leaving, check the clock before deciding on food or another nearby stop. Do not buy a multi-attraction bundle merely because the venues are close: each extra admission adds its own waiting and visiting time.</p>
      <p>If your priority is Dotonbori, Osaka Castle or a guided city outing, use the <Link href="/ports/osaka">Osaka cruise port guide</Link> to choose that as a different main plan. The city-transfer examples there are not a walking-time estimate for Kaiyukan. For the aquarium option, finish by returning through the passenger entrance confirmed by your ship, with the original return allowance intact.</p>
    </section>
    <IntentViatorCards portSlug="osaka" topic={guide.topic} portName="Osaka" heading={guide.viator.heading}
      intro="Tempo Harbor Theater is in the same waterfront area as Kaiyukan. Choose the hands-on Wadaiko Rhythm Quest workshop if you want to learn taiko drumming, or UTAGE if you prefer a performance. These require separate tickets; aquarium admission and cruise-port transport are not included. Consider either only if the complete session and walk back leave your original return allowance intact."
      bookingNote="Allow about an hour for the selected session, plus check-in and your return journey. The workshop asks you to arrive 15 minutes early and refuses entry more than five minutes late; confirm the show's instructions separately. The hands-on workshop is listed as not wheelchair accessible. Check the exact date, start and end times, participation conditions, and cancellation deadline. Some performances are late in the day: skip any session that does not fit your ship's return deadline."
      actionLabel="Check session times & tickets ↗"
      fallback={{ href: "https://www.viator.com/tours/Osaka/WA-DAIKO-RHYTHM-QUEST-Japanese-drum-experience/d333-467011P1?mcid=42383&pid=P00311056&campaign=pdg-osaka-kaiyukan-from-cruise-port&medium=api&api_version=2.0", label: "Check the taiko workshop on Viator", productCode: "467011P1", placement: "kaiyukan-nearby-taiko" }} />
    <p>Venue and schedule: <a href="https://www.tempo-harbor-theater.com/en" target="_blank" rel="noopener noreferrer">Tempo Harbor Theater</a>. The theater is at <strong>1-5-10 Kaigandori, Osaka Cultural Center, fourth floor</strong>, a separate entrance from the aquarium. Check the <a href="https://www.tempo-harbor-theater.com/wadaiko-rhythm-quest" target="_blank" rel="noopener noreferrer">workshop instructions</a> or <a href="https://www.tempo-harbor-theater.com/en/utage-live-show" target="_blank" rel="noopener noreferrer">UTAGE program</a> for the experience you select. The published UTAGE rules require guests under 16 to be accompanied by a guardian.</p>
    <p><em>Aquarium planning sources checked October 1, 2026; ticket entry points, nearby-show details and photographs reviewed October 6, 2026. This is a source-based planning guide, not a report of a personal visit. Recheck your sailing and visit date before booking.</em></p>
    <p className={styles.credit}>Header: Kaiyukan and Osaka Bay, photographed in May 2026. Photo by <a href="https://commons.wikimedia.org/wiki/File:Kaiy%C5%ABkan.jpg" target="_blank" rel="noopener noreferrer">Sakai Yayoi / Wikimedia Commons</a>, <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener noreferrer">CC0</a>; resized for web.</p>
  </div>;
}
